version: '2'
services:
  fe:
    image: kammana/emp-fe-comp:1.0
    container_name: emp-fe
    ports:
     - "4200:4200"
    networks:
      - javahome-app
  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    networks:
      - javahome-app
    volumes:
      - mongodb:/data/db
  emp-api:
    container_name: empapi
    image: kammana/boot-api:5.0
    ports:
     - "8080:8080"
    networks:
      - javahome-app
volumes:
  mongodb:
networks:
  javahome-app:
    driver: bridge
